name: Compare

on:
  workflow_dispatch:
    inputs:
      oldVersion:
        type: string
        required: true
        description: 'old version'
      newVersion:
        type: string
        required: true
        description: 'new version'

jobs:
  compare:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up fvm
        shell: bash
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Install flutter versions
        shell: bash
        run: |
          fvm install ${{ github.event.inputs.oldVersion }}
          fvm install ${{ github.event.inputs.newVersion }}

      - name: Reset and Checkout branch
        shell: bash
        run: |
          git switch -C versions/${{ github.event.inputs.oldVersion }}

      - name: Create old flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.oldVersion }}

      - name: Commit and Push old flutter project
        shell: bash
        run: |
          git add .
          git commit -m "Create flutter project"
          git push -f -u origin versions/${{ github.event.inputs.oldVersion }}

      - name: Clean old flutter template project
        shell: bash
        run: |
          ls -A | grep -v '^\.fvm$' | xargs rm -r

      - name: Create new flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.newVersion }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Compare ${{ github.event.inputs.oldVersion }} and ${{ github.event.inputs.newVersion }}'
          base: versions/${{ github.event.inputs.oldVersion }}
          branch: comparisons/${{ github.event.inputs.oldVersion }}-${{ github.event.inputs.newVersion }}
          branch-suffix: timestamp
