name: Compare

on:
  workflow_dispatch:
    inputs:
      old-version:
        type: string
        required: true
        description: 'old version'
      new-version:
        type: string
        required: true
        description: 'new version'

jobs:
  compare:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/orgs/community/discussions/26560
      - name: Set up git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # https://github.com/actions/runner-images/issues/6283
      - name: Set up Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up fvm
        shell: bash
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Install flutter versions
        shell: bash
        run: |
          fvm install ${{ github.event.inputs.old-version }}
          fvm install ${{ github.event.inputs.new-version }}

      - name: Recreate and checkout branch
        shell: bash
        run: |
          git switch -C versions/${{ github.event.inputs.old-version }}

      - name: Create old flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.old-version }}

      - name: Commit and force push old flutter template project
        shell: bash
        run: |
          git add .
          git commit -m "Create flutter template project"
          git push -f -u origin versions/${{ github.event.inputs.old-version }}

      - name: Clean old flutter template project
        shell: bash
        working-directory: template
        run: |
          ls -A | grep -v '^\.fvm$' | xargs rm -r

      - name: Create new flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.new-version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Compare ${{ github.event.inputs.old-version }} and ${{ github.event.inputs.new-version }}'
          base: versions/${{ github.event.inputs.old-version }}
          branch: comparisons/${{ github.event.inputs.old-version }}-${{ github.event.inputs.new-version }}
          branch-suffix: timestamp
