name: Compare

on:
  workflow_dispatch:
    inputs:
      old-version:
        type: string
        required: true
        description: 'old version'
      new-version:
        type: string
        required: true
        description: 'new version'

env:
  COMMIT_USER_NAME: github-actions
  COMMIT_USER_EMAIL: 41898282+github-actions@users.noreply.github.com

jobs:
  compare:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/orgs/community/discussions/26560
      - name: Set up git
        run: |
          git config --local user.name "${{ env.COMMIT_USER_NAME }}"
          git config --local user.email "${{ env.COMMIT_USER_EMAIL }}"

      # https://github.com/actions/runner-images/issues/6283
      - name: Set up Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up fvm
        shell: bash
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Install flutter versions
        shell: bash
        run: |
          fvm install ${{ github.event.inputs.old-version }}
          fvm install ${{ github.event.inputs.new-version }}

      - name: Recreate and checkout branch
        shell: bash
        run: |
          git switch -C versions/${{ github.event.inputs.old-version }}

      - name: Create old flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.old-version }}

      - name: Commit and force push old flutter template project
        shell: bash
        run: |
          git add .
          git commit -m "Create flutter template project"
          git push -f -u origin versions/${{ github.event.inputs.old-version }}

      - name: Clean old flutter template project
        shell: bash
        working-directory: template
        run: |
          ls -A | grep -v '^\.fvm$' | xargs rm -r

      - name: Create new flutter template project
        uses: ./.github/actions/create-flutter-template-project
        with:
          flutter-version: ${{ github.event.inputs.new-version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          author: ${{ env.COMMIT_USER_NAME }} <${{ env.COMMIT_USER_EMAIL }}>
          committer: ${{ env.COMMIT_USER_NAME }} <${{ env.COMMIT_USER_EMAIL }}>
          commit-message: 'Update flutter template project'
          title: 'Compare ${{ github.event.inputs.old-version }} and ${{ github.event.inputs.new-version }}'
          base: versions/${{ github.event.inputs.old-version }}
          branch: comparisons/${{ github.event.inputs.old-version }}-${{ github.event.inputs.new-version }}
          branch-suffix: timestamp
          body: |
            ## Flutter
            - [Flutter release notes](https://docs.flutter.dev/release/release-notes)
            - [Hotfixes to the Stable Channel](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel)
            - [Comparing changes](https://github.com/flutter/flutter/compare/${{ github.event.inputs.old-version }}...${{ github.event.inputs.new-version }})
            
            ## Dart
            - [What’s new](https://dart.dev/guides/whats-new)
            - [Dart language evolution](https://dart.dev/guides/language/evolution)
            - [Changelog](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md)
            - [Comparing changes](https://github.com/dart-lang/sdk/compare/)
